# 1. NumPy

## Introduction

NumPy (Numerical Python) is the fundamental library used for numerical computations in Python. It provides support for multidimensional arrays, matrices, and mathematical operations. NumPy is faster and more memory-efficient than Python lists because it stores data in contiguous memory. It offers a wide range of mathematical, statistical, and linear algebra functions that simplify complex calculations. Many popular libraries such as Pandas, SciPy, TensorFlow, and Scikit-Learn are built on top of NumPy. Due to its speed, efficiency, and powerful features, NumPy is considered the foundation of Machine Learning, Data Science, Artificial Intelligence, and scientific computing in Python.

## Import Library

```python
import numpy as np
```

## Common Functions

1. **np.array()** – Creates a NumPy array.
2. **np.zeros()** – Creates an array filled with zeros.
3. **np.ones()** – Creates an array filled with ones.
4. **np.empty()** – Creates an empty array without initializing values.
5. **np.arange()** – Generates evenly spaced values within a range.
6. **np.linspace()** – Generates evenly spaced values between two limits.
7. **np.reshape()** – Changes the shape of an array.
8. **np.flatten()** – Converts a multidimensional array into a one-dimensional array.
9. **np.transpose()** – Transposes rows and columns of an array.
10. **np.mean()** – Calculates the average value.
11. **np.median()** – Calculates the median value.
12. **np.std()** – Calculates the standard deviation.
13. **np.var()** – Calculates the variance.
14. **np.sum()** – Returns the sum of array elements.
15. **np.min()** – Returns the minimum value.
16. **np.max()** – Returns the maximum value.
17. **np.argmin()** – Returns the index of the minimum value.
18. **np.argmax()** – Returns the index of the maximum value.
19. **np.sort()** – Sorts the elements of an array.
20. **np.unique()** – Returns unique values from an array.
21. **np.concatenate()** – Joins two or more arrays.
22. **np.split()** – Splits an array into multiple sub-arrays.
23. **np.random.rand()** – Generates random decimal numbers.
24. **np.random.randint()** – Generates random integers within a specified range.
25. **np.dot()** – Performs matrix multiplication (dot product).

In [ ]:
import numpy as np

# 1. np.array()
arr = np.array([10, 20, 30, 40, 50])
print("1. Array:", arr)

# 2. np.zeros()
print("\n2. Zeros Array:\n", np.zeros((2,3)))

# 3. np.ones()
print("\n3. Ones Array:\n", np.ones((2,2)))

# 4. np.empty()
print("\n4. Empty Array:\n", np.empty((2,2)))

# 5. np.arange()
print("\n5. Arange:", np.arange(1,11,2))

# 6. np.linspace()
print("\n6. Linspace:", np.linspace(0,10,5))

# 7. np.reshape()
a = np.arange(1,13)
print("\n7. Reshape:\n", a.reshape(3,4))

# 8. np.flatten()
print("\n8. Flatten:", a.reshape(3,4).flatten())

# 9. np.transpose()
matrix = np.array([[1,2],[3,4]])
print("\n9. Transpose:\n", matrix.T)

# 10. np.mean()
print("\n10. Mean:", np.mean(arr))

# 11. np.median()
print("11. Median:", np.median(arr))

# 12. np.std()
print("12. Standard Deviation:", np.std(arr))

# 13. np.var()
print("13. Variance:", np.var(arr))

# 14. np.sum()
print("14. Sum:", np.sum(arr))

# 15. np.min()
print("15. Minimum:", np.min(arr))

# 16. np.max()
print("16. Maximum:", np.max(arr))

# 17. np.argmin()
print("17. Index of Minimum:", np.argmin(arr))

# 18. np.argmax()
print("18. Index of Maximum:", np.argmax(arr))

# 19. np.sort()
unsorted = np.array([5,2,8,1,9])
print("19. Sorted:", np.sort(unsorted))

# 20. np.unique()
dup = np.array([1,2,2,3,4,4,5])
print("20. Unique:", np.unique(dup))

# 21. np.concatenate()
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print("21. Concatenate:", np.concatenate((a1,a2)))

# 22. np.split()
arr2 = np.arange(8)
print("22. Split:", np.split(arr2,4))

# 23. np.random.rand()
print("23. Random Decimal:\n", np.random.rand(2,2))

# 24. np.random.randint()
print("24. Random Integer:\n", np.random.randint(1,100,(2,3)))

# 25. np.dot()
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("25. Dot Product:\n", np.dot(x,y))

1. Array: [10 20 30 40 50]

2. Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

3. Ones Array:
 [[1. 1.]
 [1. 1.]]

4. Empty Array:
 [[1. 1.]
 [1. 1.]]

5. Arange: [1 3 5 7 9]

6. Linspace: [ 0.   2.5  5.   7.5 10. ]

7. Reshape:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

8. Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]

9. Transpose:
 [[1 3]
 [2 4]]

10. Mean: 30.0
11. Median: 30.0
12. Standard Deviation: 14.142135623730951
13. Variance: 200.0
14. Sum: 150
15. Minimum: 10
16. Maximum: 50
17. Index of Minimum: 0
18. Index of Maximum: 4
19. Sorted: [1 2 5 8 9]
20. Unique: [1 2 3 4 5]
21. Concatenate: [1 2 3 4 5 6]
22. Split: [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]
23. Random Decimal:
 [[0.39856853 0.7719333 ]
 [0.75483667 0.5238745 ]]
24. Random Integer:
 [[21 12 84]
 [18 79 58]]
25. Dot Product:
 [[19 22]
 [43 50]]
